version: 2
jobs:
  build:
    working_directory: ~/alexandred/VoodooI2C
    parallelism: 1
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    macos:
      xcode: 11.3.0
    steps:
      # Machine Setup
      - checkout
      # Prepare for artifact and test results
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run: xcodebuild -version
      # Restore the dependency cache
      - restore_cache:
          keys:
          # This branch if available
          - v1-dep-{{ .Branch }}-
          # Default branch if not
          - v1-dep-master-
      - run:
          name: "Download the macOS 10.12 SDK"
          command: curl -L https://github.com/alexey-lysiuk/macos-sdk/releases/download/10.12/MacOSX10.12.tar.bz2 -o /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.tar.bz2 && tar -xjf /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.tar.bz2 -C /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
      - run: src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/VoodooInput/master/VoodooInput/Scripts/bootstrap.sh) && eval "$src" && mv VoodooInput Dependencies
      - run: pip install cpplint
      - run: pip install git+https://github.com/alexandred/cldoc.git
      - run: echo 'export PATH=~/Library/Python/2.7/bin:$PATH' >> ~/.bashrc
      - run: git submodule init && git submodule update
      - run: xcodebuild -workspace "VoodooI2C.xcworkspace" -scheme "VoodooI2C" -sdk macosx10.12 -derivedDataPath build clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - run: find $HOME/Library/Developer/Xcode/DerivedData -name '*.xcactivitylog' -exec cp {} $CIRCLE_ARTIFACTS/xcactivitylog \; || true
      - run:
          name: "Copy build artifacts"
          command: cp -R build/Build/Products/Release/ $CIRCLE_ARTIFACTS
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts

      - persist_to_workspace:
          root: ./
          paths:
            - build/Build/Products/Release/*
            - docs/*

  deploy:
    macos:
      xcode: 11.3.0
    steps:
      # Machine Setup
      - checkout
      - attach_workspace:
          at: ./
      - run: brew update
      - run: brew tap tcnksm/ghr
      - run: brew install ghr
      - run:
          name: "Publish Release on GitHub"
          command: export NEW_LINES=$'\n\n\n' && export LAST_TEN_COMMITS="$(git log `git describe --tags $(git rev-list --tags --max-count=1)`..HEAD --oneline --format=" - %s" | head -10)" && export NUM_COMMITS="$(git rev-list `git describe --tags $(git rev-list --tags --max-count=1)`..HEAD --count)" && cd build/Build/Products/Release && export VOODOOI2C_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "VoodooI2C.kext/Contents/info.plist") && mkdir Archives && zip -r Archives/"VoodooI2C-$VOODOOI2C_VERSION.zip" *.kext && zip -r Archives/"VoodooI2C-Debug-Symbols-$VOODOOI2C_VERSION.zip" *.dSYM && ghr -b "Since the last release there have been $NUM_COMMITS commit(s). The descriptions for the first (at most) 10 of these are as follows $NEW_LINES $LAST_TEN_COMMITS" --username alexandred --token $GITHUB_TOKEN --soft $VOODOOI2C_VERSION Archives/
      - run:
          name: "Update Documentation"
          command: mkdir docrepo && cp -R docs/* docrepo/ && cd docrepo && git init . && git remote add origin https://$DOCUMENTATION_TOKEN@github.com/VoodooI2C/VoodooI2C.github.io.git && git add . && git commit -m "add documentation" && git push -f --set-upstream origin master

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
